/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.FusekiController;
import Controlador.ModelController;
import Controlador.MongoController;
import Controlador.TDBController;


/**
 *
 * @author Azul
 */



public class CrearProducto extends javax.swing.JFrame {
    private MongoController mongocontroller;
    private FusekiController fusekicontroller;
    private ModelController modelcontroller;
    private TDBController tdb;
    /**
     * Creates new form CrearProducto
     */
    public CrearProducto(MongoController m, FusekiController f, ModelController mo, TDBController t) {
       
        initComponents();
        this.setLocationRelativeTo(null);
        this.modelcontroller=mo;
        this.mongocontroller=m;
        this.fusekicontroller=f;
        this.tdb=t;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        minimiza = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();
        atras = new javax.swing.JButton();
        id = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        marca = new javax.swing.JLabel();
        descripcion = new javax.swing.JLabel();
        modelo = new javax.swing.JLabel();
        camponombre = new javax.swing.JTextField();
        campoID = new javax.swing.JTextField();
        campomarca = new javax.swing.JTextField();
        campomodelo = new javax.swing.JTextField();
        clase = new javax.swing.JLabel();
        campoclase = new javax.swing.JTextField();
        caract = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        campodescripcion = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        campocaract = new javax.swing.JTextArea();
        guardar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(1500, 1500));

        jPanel1.setBackground(new java.awt.Color(173, 199, 228));
        jPanel1.setMaximumSize(new java.awt.Dimension(1500, 1500));
        jPanel1.setPreferredSize(new java.awt.Dimension(919, 779));

        titulo.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        titulo.setText(" Crear Producto");

        minimiza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diminish.png"))); // NOI18N
        minimiza.setBorderPainted(false);
        minimiza.setContentAreaFilled(false);

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel.png"))); // NOI18N
        cerrar.setBorderPainted(false);
        cerrar.setContentAreaFilled(false);
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/left-arrow.png"))); // NOI18N
        atras.setBorderPainted(false);
        atras.setContentAreaFilled(false);
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });

        id.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        id.setText("ID:");

        nombre.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        nombre.setText("Nombre:");

        marca.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        marca.setText("Marca:");

        descripcion.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        descripcion.setText("Descripcion:");

        modelo.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        modelo.setText("Modelo:");

        clase.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        clase.setText("Clase:");

        caract.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        caract.setText("Caracteristicas:");

        campodescripcion.setColumns(20);
        campodescripcion.setRows(5);
        jScrollPane3.setViewportView(campodescripcion);

        campocaract.setColumns(20);
        campocaract.setRows(5);
        jScrollPane4.setViewportView(campocaract);

        guardar.setText("Guardar Cambios");

        jSeparator1.setBackground(new java.awt.Color(144, 191, 242));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(atras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(minimiza, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caract)
                            .addComponent(descripcion)
                            .addComponent(clase)
                            .addComponent(modelo)
                            .addComponent(marca)
                            .addComponent(nombre)
                            .addComponent(id))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(camponombre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campomarca, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoID, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campomodelo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                            .addComponent(jScrollPane4)
                            .addComponent(campoclase)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cerrar)
                    .addComponent(minimiza)
                    .addComponent(atras, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(titulo)
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id)
                    .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(camponombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marca)
                    .addComponent(campomarca, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campomodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelo))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoclase, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clase))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descripcion)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caract))
                .addGap(65, 65, 65)
                .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1133, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JTextField campoID;
    private javax.swing.JTextArea campocaract;
    private javax.swing.JTextField campoclase;
    private javax.swing.JTextArea campodescripcion;
    private javax.swing.JTextField campomarca;
    private javax.swing.JTextField campomodelo;
    private javax.swing.JTextField camponombre;
    private javax.swing.JLabel caract;
    private javax.swing.JButton cerrar;
    private javax.swing.JLabel clase;
    private javax.swing.JLabel descripcion;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel id;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel marca;
    private javax.swing.JButton minimiza;
    private javax.swing.JLabel modelo;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
