/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.*;
import Modelo.Clase;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellRenderer;
import org.apache.jena.ontology.OntModel;
import org.apache.jena.rdf.model.Model;
import org.apache.jena.rdf.model.ModelFactory;
import org.apache.jena.rdf.model.Property;

/**
 *
 * @author ale_b
 */
public class AgregarClase extends javax.swing.JFrame {

    private ModelController model;
    private FusekiController fuseki;
    private TDBController tdb;
    private MongoController mongo;
    private JTree arbol;
    private Clase clase;
    
    /**
     * Creates new form AgregarPropiedad
     */
    public AgregarClase(ModelController m, FusekiController f,TDBController tc,MongoController mo, Clase c) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.model=m;
        this.fuseki=f;
        this.tdb=tc;
        this.mongo=mo;
        this.clase=c;
        this.subclass.setText(c.toString());
        
    }
    public void setTree(DefaultMutableTreeNode raiz, ArrayList <Clase> raices){
        
        for (Clase c: raices){
                c.setSubClasses();
                DefaultMutableTreeNode node = new DefaultMutableTreeNode(c);
                if (!node.equals(raiz)){
                    raiz.add(node);
                }
                
                if (!c.isLeaf()){
                    ArrayList<Clase> hijos= c.getHijos();
                    setTree(node, hijos);
                }
                    
        }
    }
    public void setTreeIcons(){
        DefaultTreeCellRenderer renderer = new DefaultTreeCellRenderer();
        ImageIcon leafIcon = new ImageIcon(getClass().getResource("/price-tag.png"));
        ImageIcon rootClosedIcon = new ImageIcon(getClass().getResource("/closefolder.png"));
        ImageIcon rootOpenIcon = new ImageIcon(getClass().getResource("/openfolder.png"));
        renderer.setLeafIcon(leafIcon);
        renderer.setClosedIcon(rootClosedIcon);
        renderer.setOpenIcon(rootOpenIcon);
        arbol.setCellRenderer(renderer);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombreClase = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        uri = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        subclass = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        comments = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(173, 199, 228));

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 16)); // NOI18N
        jLabel3.setText("Subclase de:");

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 16)); // NOI18N
        jLabel4.setText("URI:");

        nombreClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreClaseActionPerformed(evt);
            }
        });
        nombreClase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombreClaseKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombreClaseKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreClaseKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 16)); // NOI18N
        jLabel5.setText("Nombre de la nueva clase:");

        uri.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        guardar.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        guardar.setText("Guardar");
        guardar.setBorder(new javax.swing.border.LineBorder(java.awt.SystemColor.activeCaption, 2, true));
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        cancelar.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.setBorder(new javax.swing.border.LineBorder(java.awt.SystemColor.activeCaption, 2, true));
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        subclass.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 16)); // NOI18N
        jLabel6.setText("Comentarios:");

        comments.setColumns(20);
        comments.setRows(5);
        jScrollPane1.setViewportView(comments);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nombreClase))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(subclass, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uri))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(subclass, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(jLabel5)
                .addGap(13, 13, 13)
                .addComponent(nombreClase, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(uri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreClaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreClaseActionPerformed

    private void nombreClaseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreClaseKeyTyped

    }//GEN-LAST:event_nombreClaseKeyTyped

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed

        if (nombreClase.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe proporcionar un nombre", "Error",  JOptionPane.ERROR_MESSAGE);
        }
        else{                       
                Clase c= this.model.createClass(nombreClase.getText().replaceAll(" ",""));
                c.addLabel(nombreClase.getText());
                if (!this.comments.getText().isEmpty()) c.addComment(this.comments.getText());
                this.clase.addSubclass(c);
                
                System.out.println("comienza update");
                tdb.updateData(model.getModel().getBaseModel());
                System.out.println("comienza nuevo servidor");
                this.fuseki=new FusekiController(3030, tdb.getDataset(), "/ont");
                DefaultMutableTreeNode raiz = new DefaultMutableTreeNode(new Clase (this.model.getOntClass("http://www.w3.org/2002/07/owl#Thing")));
                ArrayList <Clase> raices = this.model.getHierarchyRootClasses();
                setTree(raiz, raices);
                this.arbol= new JTree(raiz);
                setTreeIcons();
                ModificarOntologia mo= new ModificarOntologia(fuseki, mongo, model, arbol, tdb);
                this.setVisible(false);
                mo.setVisible(true);
                
            
            
        }
        
        
        
    }//GEN-LAST:event_guardarActionPerformed
    
    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        int seleccion = JOptionPane.showOptionDialog(
        this,
        "No se aplicarán los cambios", 
        "¿Está seguro que desea cancelar?",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE,
        null,    // null para icono por defecto.
        new Object[] { "Si", "No" },   // null para YES, NO y CANCEL
        "Si");
        if (seleccion==0){
            DefaultMutableTreeNode raiz = new DefaultMutableTreeNode(new Clase (this.model.getOntClass("http://www.w3.org/2002/07/owl#Thing")));
            ArrayList <Clase> raices = this.model.getHierarchyRootClasses();
            setTree(raiz, raices);
            setTreeIcons();
            this.arbol= new JTree(raiz);
            ModificarOntologia mo= new ModificarOntologia(fuseki, mongo, model, arbol, tdb);
            this.setVisible(false);
            mo.setVisible(true);
        }
    }//GEN-LAST:event_cancelarActionPerformed

    private void nombreClaseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreClaseKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreClaseKeyPressed

    private void nombreClaseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreClaseKeyReleased
        // TODO add your handling code here:
        this.uri.setText(this.model.getUri("gpc")+nombreClase.getText().replaceAll(" ",""));
    }//GEN-LAST:event_nombreClaseKeyReleased

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JTextArea comments;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreClase;
    private javax.swing.JLabel subclass;
    private javax.swing.JLabel uri;
    // End of variables declaration//GEN-END:variables
}
