/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.*;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import org.apache.jena.ontology.OntModel;
import org.apache.jena.rdf.model.Model;
import org.apache.jena.rdf.model.ModelFactory;

/**
 *
 * @author ale_b
 */
public class AgregarPropiedad extends javax.swing.JFrame {

    private ModelController model;
    private FusekiController fuseki;
    private TDBController tdb;
    private JTree arbol;
    private MongoController mongo;
    
    /**
     * Creates new form AgregarPropiedad
     */
    public AgregarPropiedad(ModelController m, FusekiController f,TDBController tc, JTree arb, MongoController mo) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.model=m;
        this.fuseki=f;
        this.tdb=tc;
        this.arbol=arb;
        this.mongo=mo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dp = new javax.swing.JCheckBox();
        op = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        nombrePropiedad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        uri = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        comments = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(173, 199, 228));

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 16)); // NOI18N
        jLabel3.setText("Tipo de propiedad:");

        dp.setText("Datatype property");
        dp.setContentAreaFilled(false);
        dp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpActionPerformed(evt);
            }
        });

        op.setText("Object property");
        op.setContentAreaFilled(false);
        op.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 16)); // NOI18N
        jLabel4.setText("URI:");

        nombrePropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrePropiedadActionPerformed(evt);
            }
        });
        nombrePropiedad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombrePropiedadKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombrePropiedadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombrePropiedadKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 16)); // NOI18N
        jLabel5.setText("Nombre de la propiedad:");

        uri.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        guardar.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        guardar.setText("Guardar");
        guardar.setBorder(new javax.swing.border.LineBorder(java.awt.SystemColor.activeCaption, 2, true));
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        cancelar.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.setBorder(new javax.swing.border.LineBorder(java.awt.SystemColor.activeCaption, 2, true));
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 16)); // NOI18N
        jLabel6.setText("Comentarios:");

        comments.setColumns(20);
        comments.setRows(5);
        jScrollPane1.setViewportView(comments);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 235, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(dp, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombrePropiedad)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uri))
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(217, Short.MAX_VALUE)
                    .addComponent(op, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(133, 133, 133)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(19, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dp)
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addGap(13, 13, 13)
                .addComponent(nombrePropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(uri))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(op)
                    .addContainerGap(246, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(240, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(137, 137, 137)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpActionPerformed
        // TODO add your handling code here:
        if(dp.isSelected()){
            this.op.setEnabled(false);
        }
        else{
            this.op.setEnabled(true);
        }
        
    }//GEN-LAST:event_dpActionPerformed

    private void opActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opActionPerformed
        // TODO add your handling code here:
        if(op.isSelected()){
            this.dp.setEnabled(false);
        }
        else{
            this.dp.setEnabled(true);
        }
    }//GEN-LAST:event_opActionPerformed

    private void nombrePropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrePropiedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrePropiedadActionPerformed

    private void nombrePropiedadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombrePropiedadKeyTyped

    }//GEN-LAST:event_nombrePropiedadKeyTyped

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed

        if (!dp.isSelected() && !op.isSelected()){
            JOptionPane.showMessageDialog(this, "Debe elegir un tipo de propiedad", "Error",  JOptionPane.ERROR_MESSAGE);
        }
        else{
        if (nombrePropiedad.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe proporcionar un nombre", "Error",  JOptionPane.ERROR_MESSAGE);
        }
        else{
            if(op.isSelected()){
                                
                this.model.createObjectProperty(nombrePropiedad.getText(), this.comments.getText());
                System.out.println("comienza update");
                tdb.updateData(model.getModel().getBaseModel());
                System.out.println("comienza nuevo servidor");
                this.fuseki=new FusekiController(3030, tdb.getDataset(), "/ont");
                ModificarOntologia mo= new ModificarOntologia(fuseki, mongo, model, arbol, tdb);
                this.setVisible(false);
                mo.setVisible(true);
                
            }
            else{
                               
                this.model.createDatatypeProperty(nombrePropiedad.getText(), this.comments.getText());
                System.out.println("comienza update");
                tdb.updateData(model.getModel().getBaseModel());
                System.out.println("comienza nuevo servidor");
                this.fuseki=new FusekiController(3030, tdb.getDataset(), "/ont");
                ModificarOntologia mo= new ModificarOntologia(fuseki, mongo, model, arbol, tdb);
                this.setVisible(false);
                mo.setVisible(true);
                
            }
        }
        
        }
        
    }//GEN-LAST:event_guardarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        int seleccion = JOptionPane.showOptionDialog(
        this,
        "No se aplicarán los cambios", 
        "¿Está seguro que desea cancelar?",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE,
        null,    // null para icono por defecto.
        new Object[] { "Si", "No" },   // null para YES, NO y CANCEL
        "Si");
        if (seleccion==0) this.setVisible(false);
    }//GEN-LAST:event_cancelarActionPerformed

    private void nombrePropiedadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombrePropiedadKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrePropiedadKeyPressed

    private void nombrePropiedadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombrePropiedadKeyReleased
        // TODO add your handling code here:
        this.uri.setText(this.model.getUri("gr")+nombrePropiedad.getText());
    }//GEN-LAST:event_nombrePropiedadKeyReleased

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JTextArea comments;
    private javax.swing.JCheckBox dp;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombrePropiedad;
    private javax.swing.JCheckBox op;
    private javax.swing.JLabel uri;
    // End of variables declaration//GEN-END:variables
}
